//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YousignCosignService
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yousign.com")]
    public partial class YousignException
    {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.yousign.com", ConfigurationName="YousignCosignService.CosignWS")]
    public interface CosignWS
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.yousign.com/CosignWS/confirmCosignRequest", ReplyAction="http://www.yousign.com/CosignWS/confirmCosignResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(YousignCosignService.YousignException), Action="http://www.yousign.com/CosignWS/confirmCosign/Fault/YousignException", Name="YousignException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<YousignCosignService.confirmCosignResponse> confirmCosignAsync(YousignCosignService.confirmCosignRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.yousign.com/CosignWS/getInfosFromCosignatureDemandRequest", ReplyAction="http://www.yousign.com/CosignWS/getInfosFromCosignatureDemandResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(YousignCosignService.YousignException), Action="http://www.yousign.com/CosignWS/getInfosFromCosignatureDemand/Fault/YousignExcept" +
            "ion", Name="YousignException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<YousignCosignService.getInfosFromCosignatureDemandResponse> getInfosFromCosignatureDemandAsync(YousignCosignService.getInfosFromCosignatureDemandRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.yousign.com/CosignWS/getCosignedFilesFromDemandRequest", ReplyAction="http://www.yousign.com/CosignWS/getCosignedFilesFromDemandResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(YousignCosignService.YousignException), Action="http://www.yousign.com/CosignWS/getCosignedFilesFromDemand/Fault/YousignException" +
            "", Name="YousignException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<YousignCosignService.getCosignedFilesFromDemandResponse> getCosignedFilesFromDemandAsync(YousignCosignService.getCosignedFilesFromDemandRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.yousign.com/CosignWS/alertCosignersRequest", ReplyAction="http://www.yousign.com/CosignWS/alertCosignersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(YousignCosignService.YousignException), Action="http://www.yousign.com/CosignWS/alertCosigners/Fault/YousignException", Name="YousignException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<YousignCosignService.alertCosignersResponse> alertCosignersAsync(YousignCosignService.alertCosignersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.yousign.com/CosignWS/cancelCosignatureDemandRequest", ReplyAction="http://www.yousign.com/CosignWS/cancelCosignatureDemandResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(YousignCosignService.YousignException), Action="http://www.yousign.com/CosignWS/cancelCosignatureDemand/Fault/YousignException", Name="YousignException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<YousignCosignService.cancelCosignatureDemandResponse> cancelCosignatureDemandAsync(YousignCosignService.cancelCosignatureDemandRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.yousign.com/CosignWS/isPDFSignableRequest", ReplyAction="http://www.yousign.com/CosignWS/isPDFSignableResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(YousignCosignService.YousignException), Action="http://www.yousign.com/CosignWS/isPDFSignable/Fault/YousignException", Name="YousignException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<YousignCosignService.isPDFSignableResponse> isPDFSignableAsync(YousignCosignService.isPDFSignableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.yousign.com/CosignWS/updateCosignerRequest", ReplyAction="http://www.yousign.com/CosignWS/updateCosignerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(YousignCosignService.YousignException), Action="http://www.yousign.com/CosignWS/updateCosigner/Fault/YousignException", Name="YousignException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<YousignCosignService.updateCosignerResponse> updateCosignerAsync(YousignCosignService.updateCosignerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.yousign.com/CosignWS/initCosignRequest", ReplyAction="http://www.yousign.com/CosignWS/initCosignResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(YousignCosignService.YousignException), Action="http://www.yousign.com/CosignWS/initCosign/Fault/YousignException", Name="YousignException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<YousignCosignService.initCosignResponse> initCosignAsync(YousignCosignService.initCosignRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.yousign.com/CosignWS/addTextToWriteRequest", ReplyAction="http://www.yousign.com/CosignWS/addTextToWriteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(YousignCosignService.YousignException), Action="http://www.yousign.com/CosignWS/addTextToWrite/Fault/YousignException", Name="YousignException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<YousignCosignService.addTextToWriteResponse> addTextToWriteAsync(YousignCosignService.addTextToWriteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.yousign.com/CosignWS/cosignRequest", ReplyAction="http://www.yousign.com/CosignWS/cosignResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(YousignCosignService.YousignException), Action="http://www.yousign.com/CosignWS/cosign/Fault/YousignException", Name="YousignException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<YousignCosignService.cosignResponse> cosignAsync(YousignCosignService.cosignRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.yousign.com/CosignWS/getListCosignRequest", ReplyAction="http://www.yousign.com/CosignWS/getListCosignResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(YousignCosignService.YousignException), Action="http://www.yousign.com/CosignWS/getListCosign/Fault/YousignException", Name="YousignException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<YousignCosignService.getListCosignResponse> getListCosignAsync(YousignCosignService.getListCosignRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.yousign.com/CosignWS/addFileRequest", ReplyAction="http://www.yousign.com/CosignWS/addFileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(YousignCosignService.YousignException), Action="http://www.yousign.com/CosignWS/addFile/Fault/YousignException", Name="YousignException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<YousignCosignService.addFileResponse> addFileAsync(YousignCosignService.addFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="confirmCosign", WrapperNamespace="http://www.yousign.com", IsWrapped=true)]
    public partial class confirmCosignRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idDemand;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cosignerMail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string strAuthParam;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] signatureImage;
        
        public confirmCosignRequest()
        {
        }
        
        public confirmCosignRequest(int idDemand, string token, string cosignerMail, string strAuthParam, byte[] signatureImage)
        {
            this.idDemand = idDemand;
            this.token = token;
            this.cosignerMail = cosignerMail;
            this.strAuthParam = strAuthParam;
            this.signatureImage = signatureImage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="confirmCosignResponse", WrapperNamespace="http://www.yousign.com", IsWrapped=true)]
    public partial class confirmCosignResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public confirmCosignResponse()
        {
        }
        
        public confirmCosignResponse(bool @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yousign.com")]
    public partial class InfosDemandResp
    {
        
        private FileSignedInfosResp[] fileInfosField;
        
        private System.DateTime dateCreationField;
        
        private bool dateCreationFieldSpecified;
        
        private string descriptionField;
        
        private string statusField;
        
        private CosignerInfosResp[] cosignerInfosField;
        
        private Initiator initiatorField;
        
        private string titleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fileInfos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public FileSignedInfosResp[] fileInfos
        {
            get
            {
                return this.fileInfosField;
            }
            set
            {
                this.fileInfosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime dateCreation
        {
            get
            {
                return this.dateCreationField;
            }
            set
            {
                this.dateCreationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateCreationSpecified
        {
            get
            {
                return this.dateCreationFieldSpecified;
            }
            set
            {
                this.dateCreationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cosignerInfos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public CosignerInfosResp[] cosignerInfos
        {
            get
            {
                return this.cosignerInfosField;
            }
            set
            {
                this.cosignerInfosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public Initiator initiator
        {
            get
            {
                return this.initiatorField;
            }
            set
            {
                this.initiatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yousign.com")]
    public partial class FileSignedInfosResp
    {
        
        private int idFileField;
        
        private string fileNameField;
        
        private CosignersWithStatusResp[] cosignersWithStatusField;
        
        private string iuaField;
        
        private string pdfPasswordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idFile
        {
            get
            {
                return this.idFileField;
            }
            set
            {
                this.idFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cosignersWithStatus", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public CosignersWithStatusResp[] cosignersWithStatus
        {
            get
            {
                return this.cosignersWithStatusField;
            }
            set
            {
                this.cosignersWithStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string iua
        {
            get
            {
                return this.iuaField;
            }
            set
            {
                this.iuaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string pdfPassword
        {
            get
            {
                return this.pdfPasswordField;
            }
            set
            {
                this.pdfPasswordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yousign.com")]
    public partial class CosignersWithStatusResp
    {
        
        private int idField;
        
        private string statusField;
        
        private System.DateTime signatureDateField;
        
        private bool signatureDateFieldSpecified;
        
        private string textToWriteField;
        
        private bool isTextToWriteField;
        
        private bool isTextToWriteFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime signatureDate
        {
            get
            {
                return this.signatureDateField;
            }
            set
            {
                this.signatureDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool signatureDateSpecified
        {
            get
            {
                return this.signatureDateFieldSpecified;
            }
            set
            {
                this.signatureDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string textToWrite
        {
            get
            {
                return this.textToWriteField;
            }
            set
            {
                this.textToWriteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool isTextToWrite
        {
            get
            {
                return this.isTextToWriteField;
            }
            set
            {
                this.isTextToWriteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isTextToWriteSpecified
        {
            get
            {
                return this.isTextToWriteFieldSpecified;
            }
            set
            {
                this.isTextToWriteFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yousign.com")]
    public partial class CosignerInfosResp
    {
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string mailField;
        
        private string proofLevelField;
        
        private bool isCosignerCallingField;
        
        private bool isCosignerCallingFieldSpecified;
        
        private int idField;
        
        private string phoneField;
        
        private string tokenField;
        
        private string authenticationmodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string firstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string lastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string mail
        {
            get
            {
                return this.mailField;
            }
            set
            {
                this.mailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string proofLevel
        {
            get
            {
                return this.proofLevelField;
            }
            set
            {
                this.proofLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool isCosignerCalling
        {
            get
            {
                return this.isCosignerCallingField;
            }
            set
            {
                this.isCosignerCallingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isCosignerCallingSpecified
        {
            get
            {
                return this.isCosignerCallingFieldSpecified;
            }
            set
            {
                this.isCosignerCallingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string authenticationmode
        {
            get
            {
                return this.authenticationmodeField;
            }
            set
            {
                this.authenticationmodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yousign.com")]
    public partial class Initiator
    {
        
        private string nameField;
        
        private string emailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getInfosFromCosignatureDemand", WrapperNamespace="http://www.yousign.com", IsWrapped=true)]
    public partial class getInfosFromCosignatureDemandRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idDemand;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token;
        
        public getInfosFromCosignatureDemandRequest()
        {
        }
        
        public getInfosFromCosignatureDemandRequest(int idDemand, string token)
        {
            this.idDemand = idDemand;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getInfosFromCosignatureDemandResponse", WrapperNamespace="http://www.yousign.com", IsWrapped=true)]
    public partial class getInfosFromCosignatureDemandResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public YousignCosignService.InfosDemandResp @return;
        
        public getInfosFromCosignatureDemandResponse()
        {
        }
        
        public getInfosFromCosignatureDemandResponse(YousignCosignService.InfosDemandResp @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yousign.com")]
    public partial class FileSignedResp
    {
        
        private byte[] fileField;
        
        private string fileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] file
        {
            get
            {
                return this.fileField;
            }
            set
            {
                this.fileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCosignedFilesFromDemand", WrapperNamespace="http://www.yousign.com", IsWrapped=true)]
    public partial class getCosignedFilesFromDemandRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idDemand;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idFile;
        
        public getCosignedFilesFromDemandRequest()
        {
        }
        
        public getCosignedFilesFromDemandRequest(int idDemand, string token, int idFile)
        {
            this.idDemand = idDemand;
            this.token = token;
            this.idFile = idFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCosignedFilesFromDemandResponse", WrapperNamespace="http://www.yousign.com", IsWrapped=true)]
    public partial class getCosignedFilesFromDemandResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public YousignCosignService.FileSignedResp[] @return;
        
        public getCosignedFilesFromDemandResponse()
        {
        }
        
        public getCosignedFilesFromDemandResponse(YousignCosignService.FileSignedResp[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="alertCosigners", WrapperNamespace="http://www.yousign.com", IsWrapped=true)]
    public partial class alertCosignersRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idDemand;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mailSubject;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string language;
        
        public alertCosignersRequest()
        {
        }
        
        public alertCosignersRequest(int idDemand, string mailSubject, string mail, string language)
        {
            this.idDemand = idDemand;
            this.mailSubject = mailSubject;
            this.mail = mail;
            this.language = language;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="alertCosignersResponse", WrapperNamespace="http://www.yousign.com", IsWrapped=true)]
    public partial class alertCosignersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public alertCosignersResponse()
        {
        }
        
        public alertCosignersResponse(bool @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelCosignatureDemand", WrapperNamespace="http://www.yousign.com", IsWrapped=true)]
    public partial class cancelCosignatureDemandRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idDemand;
        
        public cancelCosignatureDemandRequest()
        {
        }
        
        public cancelCosignatureDemandRequest(int idDemand)
        {
            this.idDemand = idDemand;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelCosignatureDemandResponse", WrapperNamespace="http://www.yousign.com", IsWrapped=true)]
    public partial class cancelCosignatureDemandResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public cancelCosignatureDemandResponse()
        {
        }
        
        public cancelCosignatureDemandResponse(bool @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="isPDFSignable", WrapperNamespace="http://www.yousign.com", IsWrapped=true)]
    public partial class isPDFSignableRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] pdfFile;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pdfPassword;
        
        public isPDFSignableRequest()
        {
        }
        
        public isPDFSignableRequest(byte[] pdfFile, string pdfPassword)
        {
            this.pdfFile = pdfFile;
            this.pdfPassword = pdfPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="isPDFSignableResponse", WrapperNamespace="http://www.yousign.com", IsWrapped=true)]
    public partial class isPDFSignableResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public isPDFSignableResponse()
        {
        }
        
        public isPDFSignableResponse(bool @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yousign.com")]
    public partial class CosignerInfosParams
    {
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string mailField;
        
        private string phoneField;
        
        private string proofLevelField;
        
        private string authenticationModeField;
        
        private string authenticationValueField;
        
        private string persoSmsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string firstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string lastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string mail
        {
            get
            {
                return this.mailField;
            }
            set
            {
                this.mailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string proofLevel
        {
            get
            {
                return this.proofLevelField;
            }
            set
            {
                this.proofLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string authenticationMode
        {
            get
            {
                return this.authenticationModeField;
            }
            set
            {
                this.authenticationModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string authenticationValue
        {
            get
            {
                return this.authenticationValueField;
            }
            set
            {
                this.authenticationValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string persoSms
        {
            get
            {
                return this.persoSmsField;
            }
            set
            {
                this.persoSmsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateCosigner", WrapperNamespace="http://www.yousign.com", IsWrapped=true)]
    public partial class updateCosignerRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public YousignCosignService.CosignerInfosParams cosignerInfos;
        
        public updateCosignerRequest()
        {
        }
        
        public updateCosignerRequest(string token, YousignCosignService.CosignerInfosParams cosignerInfos)
        {
            this.token = token;
            this.cosignerInfos = cosignerInfos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateCosignerResponse", WrapperNamespace="http://www.yousign.com", IsWrapped=true)]
    public partial class updateCosignerResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public updateCosignerResponse()
        {
        }
        
        public updateCosignerResponse(bool @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yousign.com")]
    public partial class CosignFileParams
    {
        
        private string nameField;
        
        private byte[] contentField;
        
        private VisibleOptionsParams[] visibleOptionsField;
        
        private string pdfPasswordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
        public byte[] content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("visibleOptions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public VisibleOptionsParams[] visibleOptions
        {
            get
            {
                return this.visibleOptionsField;
            }
            set
            {
                this.visibleOptionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string pdfPassword
        {
            get
            {
                return this.pdfPasswordField;
            }
            set
            {
                this.pdfPasswordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yousign.com")]
    public partial class VisibleOptionsParams
    {
        
        private int visibleSignaturePageField;
        
        private bool isVisibleSignatureField;
        
        private string visibleRectangleSignatureField;
        
        private string visibleSignatureFieldNameField;
        
        private string mailField;
        
        private string reasonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int visibleSignaturePage
        {
            get
            {
                return this.visibleSignaturePageField;
            }
            set
            {
                this.visibleSignaturePageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool isVisibleSignature
        {
            get
            {
                return this.isVisibleSignatureField;
            }
            set
            {
                this.isVisibleSignatureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string visibleRectangleSignature
        {
            get
            {
                return this.visibleRectangleSignatureField;
            }
            set
            {
                this.visibleRectangleSignatureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string visibleSignatureFieldName
        {
            get
            {
                return this.visibleSignatureFieldNameField;
            }
            set
            {
                this.visibleSignatureFieldNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string mail
        {
            get
            {
                return this.mailField;
            }
            set
            {
                this.mailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string reason
        {
            get
            {
                return this.reasonField;
            }
            set
            {
                this.reasonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yousign.com")]
    public partial class InitCosignResp
    {
        
        private int idDemandField;
        
        private FileInfosResp[] fileInfosField;
        
        private TokenInfosResp[] tokensField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idDemand
        {
            get
            {
                return this.idDemandField;
            }
            set
            {
                this.idDemandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fileInfos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public FileInfosResp[] fileInfos
        {
            get
            {
                return this.fileInfosField;
            }
            set
            {
                this.fileInfosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tokens", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public TokenInfosResp[] tokens
        {
            get
            {
                return this.tokensField;
            }
            set
            {
                this.tokensField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yousign.com")]
    public partial class FileInfosResp
    {
        
        private int idFileField;
        
        private string fileNameField;
        
        private string sha1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idFile
        {
            get
            {
                return this.idFileField;
            }
            set
            {
                this.idFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string sha1
        {
            get
            {
                return this.sha1Field;
            }
            set
            {
                this.sha1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yousign.com")]
    public partial class TokenInfosResp
    {
        
        private string tokenField;
        
        private string mailField;
        
        private string phoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string mail
        {
            get
            {
                return this.mailField;
            }
            set
            {
                this.mailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="initCosign", WrapperNamespace="http://www.yousign.com", IsWrapped=true)]
    public partial class initCosignRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("lstCosignedFile", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public YousignCosignService.CosignFileParams[] lstCosignedFile;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("lstCosignerInfos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public YousignCosignService.CosignerInfosParams[] lstCosignerInfos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string title;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string initMailSubject;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string initMail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string endMailSubject;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string endMail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string language;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool archive;
        
        public initCosignRequest()
        {
        }
        
        public initCosignRequest(YousignCosignService.CosignFileParams[] lstCosignedFile, YousignCosignService.CosignerInfosParams[] lstCosignerInfos, string message, string title, string initMailSubject, string initMail, string endMailSubject, string endMail, string language, string mode, bool archive)
        {
            this.lstCosignedFile = lstCosignedFile;
            this.lstCosignerInfos = lstCosignerInfos;
            this.message = message;
            this.title = title;
            this.initMailSubject = initMailSubject;
            this.initMail = initMail;
            this.endMailSubject = endMailSubject;
            this.endMail = endMail;
            this.language = language;
            this.mode = mode;
            this.archive = archive;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="initCosignResponse", WrapperNamespace="http://www.yousign.com", IsWrapped=true)]
    public partial class initCosignResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public YousignCosignService.InitCosignResp @return;
        
        public initCosignResponse()
        {
        }
        
        public initCosignResponse(YousignCosignService.InitCosignResp @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addTextToWrite", WrapperNamespace="http://www.yousign.com", IsWrapped=true)]
    public partial class addTextToWriteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idFile;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string text;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool status;
        
        public addTextToWriteRequest()
        {
        }
        
        public addTextToWriteRequest(string token, int idFile, string text, bool status)
        {
            this.token = token;
            this.idFile = idFile;
            this.text = text;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addTextToWriteResponse", WrapperNamespace="http://www.yousign.com", IsWrapped=true)]
    public partial class addTextToWriteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public addTextToWriteResponse()
        {
        }
        
        public addTextToWriteResponse(bool @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yousign.com")]
    public partial class CosignOptionsParams
    {
        
        private int fileField;
        
        private string reasonField;
        
        private string locationField;
        
        private string userPasswordField;
        
        private string ownerPasswordField;
        
        private bool isRefusedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int file
        {
            get
            {
                return this.fileField;
            }
            set
            {
                this.fileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string reason
        {
            get
            {
                return this.reasonField;
            }
            set
            {
                this.reasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string userPassword
        {
            get
            {
                return this.userPasswordField;
            }
            set
            {
                this.userPasswordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ownerPassword
        {
            get
            {
                return this.ownerPasswordField;
            }
            set
            {
                this.ownerPasswordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool isRefused
        {
            get
            {
                return this.isRefusedField;
            }
            set
            {
                this.isRefusedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cosign", WrapperNamespace="http://www.yousign.com", IsWrapped=true)]
    public partial class cosignRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idDemand;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cosignerMail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("lstCosignParameters", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public YousignCosignService.CosignOptionsParams[] lstCosignParameters;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string message;
        
        public cosignRequest()
        {
        }
        
        public cosignRequest(int idDemand, string token, string cosignerMail, YousignCosignService.CosignOptionsParams[] lstCosignParameters, string message)
        {
            this.idDemand = idDemand;
            this.token = token;
            this.cosignerMail = cosignerMail;
            this.lstCosignParameters = lstCosignParameters;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cosignResponse", WrapperNamespace="http://www.yousign.com", IsWrapped=true)]
    public partial class cosignResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public cosignResponse()
        {
        }
        
        public cosignResponse(bool @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yousign.com")]
    public partial class LightInfosDemandResp
    {
        
        private FileSignedInfosResp[] fileInfosField;
        
        private System.DateTime dateCreationField;
        
        private bool dateCreationFieldSpecified;
        
        private string statusField;
        
        private CosignerLightInfosResp[] cosignerInfosField;
        
        private Initiator initiatorField;
        
        private int cosignatureEventField;
        
        private bool cosignatureEventFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fileInfos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public FileSignedInfosResp[] fileInfos
        {
            get
            {
                return this.fileInfosField;
            }
            set
            {
                this.fileInfosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime dateCreation
        {
            get
            {
                return this.dateCreationField;
            }
            set
            {
                this.dateCreationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateCreationSpecified
        {
            get
            {
                return this.dateCreationFieldSpecified;
            }
            set
            {
                this.dateCreationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cosignerInfos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public CosignerLightInfosResp[] cosignerInfos
        {
            get
            {
                return this.cosignerInfosField;
            }
            set
            {
                this.cosignerInfosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public Initiator initiator
        {
            get
            {
                return this.initiatorField;
            }
            set
            {
                this.initiatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int cosignatureEvent
        {
            get
            {
                return this.cosignatureEventField;
            }
            set
            {
                this.cosignatureEventField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cosignatureEventSpecified
        {
            get
            {
                return this.cosignatureEventFieldSpecified;
            }
            set
            {
                this.cosignatureEventFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yousign.com")]
    public partial class CosignerLightInfosResp
    {
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string mailField;
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string firstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string lastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string mail
        {
            get
            {
                return this.mailField;
            }
            set
            {
                this.mailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getListCosign", WrapperNamespace="http://www.yousign.com", IsWrapped=true)]
    public partial class getListCosignRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string search;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int firstResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int count;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime dateBegin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime dateEnd;
        
        public getListCosignRequest()
        {
        }
        
        public getListCosignRequest(string search, int firstResult, int count, string status, System.DateTime dateBegin, System.DateTime dateEnd)
        {
            this.search = search;
            this.firstResult = firstResult;
            this.count = count;
            this.status = status;
            this.dateBegin = dateBegin;
            this.dateEnd = dateEnd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getListCosignResponse", WrapperNamespace="http://www.yousign.com", IsWrapped=true)]
    public partial class getListCosignResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public YousignCosignService.LightInfosDemandResp[] @return;
        
        public getListCosignResponse()
        {
        }
        
        public getListCosignResponse(YousignCosignService.LightInfosDemandResp[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addFile", WrapperNamespace="http://www.yousign.com", IsWrapped=true)]
    public partial class addFileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("lstCosignedFile", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public YousignCosignService.CosignFileParams[] lstCosignedFile;
        
        public addFileRequest()
        {
        }
        
        public addFileRequest(string token, YousignCosignService.CosignFileParams[] lstCosignedFile)
        {
            this.token = token;
            this.lstCosignedFile = lstCosignedFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addFileResponse", WrapperNamespace="http://www.yousign.com", IsWrapped=true)]
    public partial class addFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yousign.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public YousignCosignService.FileInfosResp[] @return;
        
        public addFileResponse()
        {
        }
        
        public addFileResponse(YousignCosignService.FileInfosResp[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public interface CosignWSChannel : YousignCosignService.CosignWS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public partial class CosignWSClient : System.ServiceModel.ClientBase<YousignCosignService.CosignWS>, YousignCosignService.CosignWS
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CosignWSClient() : 
                base(CosignWSClient.GetDefaultBinding(), CosignWSClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.CosignWSPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CosignWSClient(EndpointConfiguration endpointConfiguration) : 
                base(CosignWSClient.GetBindingForEndpoint(endpointConfiguration), CosignWSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CosignWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CosignWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CosignWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CosignWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CosignWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YousignCosignService.confirmCosignResponse> YousignCosignService.CosignWS.confirmCosignAsync(YousignCosignService.confirmCosignRequest request)
        {
            return base.Channel.confirmCosignAsync(request);
        }
        
        public System.Threading.Tasks.Task<YousignCosignService.confirmCosignResponse> confirmCosignAsync(int idDemand, string token, string cosignerMail, string strAuthParam, byte[] signatureImage)
        {
            YousignCosignService.confirmCosignRequest inValue = new YousignCosignService.confirmCosignRequest();
            inValue.idDemand = idDemand;
            inValue.token = token;
            inValue.cosignerMail = cosignerMail;
            inValue.strAuthParam = strAuthParam;
            inValue.signatureImage = signatureImage;
            return ((YousignCosignService.CosignWS)(this)).confirmCosignAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YousignCosignService.getInfosFromCosignatureDemandResponse> YousignCosignService.CosignWS.getInfosFromCosignatureDemandAsync(YousignCosignService.getInfosFromCosignatureDemandRequest request)
        {
            return base.Channel.getInfosFromCosignatureDemandAsync(request);
        }
        
        public System.Threading.Tasks.Task<YousignCosignService.getInfosFromCosignatureDemandResponse> getInfosFromCosignatureDemandAsync(int idDemand, string token)
        {
            YousignCosignService.getInfosFromCosignatureDemandRequest inValue = new YousignCosignService.getInfosFromCosignatureDemandRequest();
            inValue.idDemand = idDemand;
            inValue.token = token;
            return ((YousignCosignService.CosignWS)(this)).getInfosFromCosignatureDemandAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YousignCosignService.getCosignedFilesFromDemandResponse> YousignCosignService.CosignWS.getCosignedFilesFromDemandAsync(YousignCosignService.getCosignedFilesFromDemandRequest request)
        {
            return base.Channel.getCosignedFilesFromDemandAsync(request);
        }
        
        public System.Threading.Tasks.Task<YousignCosignService.getCosignedFilesFromDemandResponse> getCosignedFilesFromDemandAsync(int idDemand, string token, int idFile)
        {
            YousignCosignService.getCosignedFilesFromDemandRequest inValue = new YousignCosignService.getCosignedFilesFromDemandRequest();
            inValue.idDemand = idDemand;
            inValue.token = token;
            inValue.idFile = idFile;
            return ((YousignCosignService.CosignWS)(this)).getCosignedFilesFromDemandAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YousignCosignService.alertCosignersResponse> YousignCosignService.CosignWS.alertCosignersAsync(YousignCosignService.alertCosignersRequest request)
        {
            return base.Channel.alertCosignersAsync(request);
        }
        
        public System.Threading.Tasks.Task<YousignCosignService.alertCosignersResponse> alertCosignersAsync(int idDemand, string mailSubject, string mail, string language)
        {
            YousignCosignService.alertCosignersRequest inValue = new YousignCosignService.alertCosignersRequest();
            inValue.idDemand = idDemand;
            inValue.mailSubject = mailSubject;
            inValue.mail = mail;
            inValue.language = language;
            return ((YousignCosignService.CosignWS)(this)).alertCosignersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YousignCosignService.cancelCosignatureDemandResponse> YousignCosignService.CosignWS.cancelCosignatureDemandAsync(YousignCosignService.cancelCosignatureDemandRequest request)
        {
            return base.Channel.cancelCosignatureDemandAsync(request);
        }
        
        public System.Threading.Tasks.Task<YousignCosignService.cancelCosignatureDemandResponse> cancelCosignatureDemandAsync(int idDemand)
        {
            YousignCosignService.cancelCosignatureDemandRequest inValue = new YousignCosignService.cancelCosignatureDemandRequest();
            inValue.idDemand = idDemand;
            return ((YousignCosignService.CosignWS)(this)).cancelCosignatureDemandAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YousignCosignService.isPDFSignableResponse> YousignCosignService.CosignWS.isPDFSignableAsync(YousignCosignService.isPDFSignableRequest request)
        {
            return base.Channel.isPDFSignableAsync(request);
        }
        
        public System.Threading.Tasks.Task<YousignCosignService.isPDFSignableResponse> isPDFSignableAsync(byte[] pdfFile, string pdfPassword)
        {
            YousignCosignService.isPDFSignableRequest inValue = new YousignCosignService.isPDFSignableRequest();
            inValue.pdfFile = pdfFile;
            inValue.pdfPassword = pdfPassword;
            return ((YousignCosignService.CosignWS)(this)).isPDFSignableAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YousignCosignService.updateCosignerResponse> YousignCosignService.CosignWS.updateCosignerAsync(YousignCosignService.updateCosignerRequest request)
        {
            return base.Channel.updateCosignerAsync(request);
        }
        
        public System.Threading.Tasks.Task<YousignCosignService.updateCosignerResponse> updateCosignerAsync(string token, YousignCosignService.CosignerInfosParams cosignerInfos)
        {
            YousignCosignService.updateCosignerRequest inValue = new YousignCosignService.updateCosignerRequest();
            inValue.token = token;
            inValue.cosignerInfos = cosignerInfos;
            return ((YousignCosignService.CosignWS)(this)).updateCosignerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YousignCosignService.initCosignResponse> YousignCosignService.CosignWS.initCosignAsync(YousignCosignService.initCosignRequest request)
        {
            return base.Channel.initCosignAsync(request);
        }
        
        public System.Threading.Tasks.Task<YousignCosignService.initCosignResponse> initCosignAsync(YousignCosignService.CosignFileParams[] lstCosignedFile, YousignCosignService.CosignerInfosParams[] lstCosignerInfos, string message, string title, string initMailSubject, string initMail, string endMailSubject, string endMail, string language, string mode, bool archive)
        {
            YousignCosignService.initCosignRequest inValue = new YousignCosignService.initCosignRequest();
            inValue.lstCosignedFile = lstCosignedFile;
            inValue.lstCosignerInfos = lstCosignerInfos;
            inValue.message = message;
            inValue.title = title;
            inValue.initMailSubject = initMailSubject;
            inValue.initMail = initMail;
            inValue.endMailSubject = endMailSubject;
            inValue.endMail = endMail;
            inValue.language = language;
            inValue.mode = mode;
            inValue.archive = archive;
            return ((YousignCosignService.CosignWS)(this)).initCosignAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YousignCosignService.addTextToWriteResponse> YousignCosignService.CosignWS.addTextToWriteAsync(YousignCosignService.addTextToWriteRequest request)
        {
            return base.Channel.addTextToWriteAsync(request);
        }
        
        public System.Threading.Tasks.Task<YousignCosignService.addTextToWriteResponse> addTextToWriteAsync(string token, int idFile, string text, bool status)
        {
            YousignCosignService.addTextToWriteRequest inValue = new YousignCosignService.addTextToWriteRequest();
            inValue.token = token;
            inValue.idFile = idFile;
            inValue.text = text;
            inValue.status = status;
            return ((YousignCosignService.CosignWS)(this)).addTextToWriteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YousignCosignService.cosignResponse> YousignCosignService.CosignWS.cosignAsync(YousignCosignService.cosignRequest request)
        {
            return base.Channel.cosignAsync(request);
        }
        
        public System.Threading.Tasks.Task<YousignCosignService.cosignResponse> cosignAsync(int idDemand, string token, string cosignerMail, YousignCosignService.CosignOptionsParams[] lstCosignParameters, string message)
        {
            YousignCosignService.cosignRequest inValue = new YousignCosignService.cosignRequest();
            inValue.idDemand = idDemand;
            inValue.token = token;
            inValue.cosignerMail = cosignerMail;
            inValue.lstCosignParameters = lstCosignParameters;
            inValue.message = message;
            return ((YousignCosignService.CosignWS)(this)).cosignAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YousignCosignService.getListCosignResponse> YousignCosignService.CosignWS.getListCosignAsync(YousignCosignService.getListCosignRequest request)
        {
            return base.Channel.getListCosignAsync(request);
        }
        
        public System.Threading.Tasks.Task<YousignCosignService.getListCosignResponse> getListCosignAsync(string search, int firstResult, int count, string status, System.DateTime dateBegin, System.DateTime dateEnd)
        {
            YousignCosignService.getListCosignRequest inValue = new YousignCosignService.getListCosignRequest();
            inValue.search = search;
            inValue.firstResult = firstResult;
            inValue.count = count;
            inValue.status = status;
            inValue.dateBegin = dateBegin;
            inValue.dateEnd = dateEnd;
            return ((YousignCosignService.CosignWS)(this)).getListCosignAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YousignCosignService.addFileResponse> YousignCosignService.CosignWS.addFileAsync(YousignCosignService.addFileRequest request)
        {
            return base.Channel.addFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<YousignCosignService.addFileResponse> addFileAsync(string token, YousignCosignService.CosignFileParams[] lstCosignedFile)
        {
            YousignCosignService.addFileRequest inValue = new YousignCosignService.addFileRequest();
            inValue.token = token;
            inValue.lstCosignedFile = lstCosignedFile;
            return ((YousignCosignService.CosignWS)(this)).addFileAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CosignWSPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CosignWSPort))
            {
                return new System.ServiceModel.EndpointAddress("https://apidemo.yousign.fr:8181/CosignWS/CosignWS");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CosignWSClient.GetBindingForEndpoint(EndpointConfiguration.CosignWSPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CosignWSClient.GetEndpointAddress(EndpointConfiguration.CosignWSPort);
        }
        
        public enum EndpointConfiguration
        {
            
            CosignWSPort,
        }
    }
}
